"""Generate THIRD_PARTY_LICENSES: Python runtime dependencies and their licenses.

Run with the interpreter of the .venv created by install.ps1, so that its installed
packages are listed:

    .venv\\Scripts\\python.exe tools\\gen_third_party_licenses.py
"""

from importlib.metadata import distributions
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Packaging and test tools: not part of the application.
SKIP = {"pip", "setuptools", "wheel", "pytest", "pluggy", "iniconfig"}


def python_license(meta) -> str:
    if meta.get("License-Expression"):
        return meta["License-Expression"]
    classifiers = [c.split(" :: ")[-1] for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return " / ".join(classifiers)
    return (meta.get("License") or "UNKNOWN").splitlines()[0][:80]


def python_url(meta) -> str:
    urls = [u.split(",", 1)[-1].strip() for u in meta.get_all("Project-URL") or []]
    return meta.get("Home-page") or (urls[0] if urls else "")


def python_rows():
    rows = {}
    for d in distributions():
        m = d.metadata
        if m["Name"].lower() in SKIP:
            continue
        rows[m["Name"].lower()] = (m["Name"], m["Version"], python_license(m), python_url(m))
    return sorted(rows.values(), key=lambda r: r[0].lower())


def table(rows):
    w = [max(len(str(r[i])) for r in rows) for i in range(3)]
    return "\n".join(f"{n:<{w[0]}}  {v:<{w[1]}}  {lic:<{w[2]}}  {url}".rstrip() for n, v, lic, url in rows)


def main():
    py = python_rows()
    text = f"""THIRD-PARTY SOFTWARE NOTICES
============================

PEOscillo is licensed under the Apache License 2.0 (see LICENSE and NOTICE).
It uses the third-party open-source packages listed below, each distributed
under its own license. The full license text of each package ships with the
package itself (*.dist-info/). Development tools (pytest...) are not listed.

Note: PyQt5 is distributed under the GNU GPL v3. The source code of PEOscillo is
Apache-2.0; a binary bundle that includes PyQt5 (the Windows folder of the
Releases) must comply with the GPL v3 as a whole.

Generated by tools/gen_third_party_licenses.py — do not edit by hand.


Python packages ({len(py)})
--------------------

{table(py)}
"""
    (ROOT / "THIRD_PARTY_LICENSES").write_text(text, encoding="utf-8")
    print(f"OK: {len(py)} Python packages -> THIRD_PARTY_LICENSES")


if __name__ == "__main__":
    main()
